apiVersion: apps/v1
kind: Deployment
metadata:
  name: h2-deployment
  labels:
    app: h2
spec:
  replicas: 1
  template:
    metadata:
      name: h2
      labels:
        app: h2
    spec:
      containers:
        - name: h2
          image: oscarfonts/h2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 1521
              hostPort: 1521
            - containerPort: 81
              hostPort: 9090
          env:
            - name: H2_OPTIONS
              value: -ifNotExists
      restartPolicy: Always
  selector:
    matchLabels:
      app: h2
