apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-zeppelin-deployment
  labels:
    app: spark-zeppelin
spec:
  replicas: 1
  template:
    metadata:
      name: spark-zeppelin
      labels:
        app: spark-zeppelin
    spec:
      containers:
        - name: spark-zeppelin
          image: apache/zeppelin:0.8.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4040
              name: zeppelin-port
            - containerPort: 8080
              name: zeppelin-web
          env:
            - name: ZEPPELIN_NOTEBOOK_DIR
              value: /notebook
            - name: ZEPPELIN_LOG_DIR
              value: /logs
          command:
            - /zeppelin/bin/zeppelin.sh
          volumeMounts:
            - mountPath: $PWD/logs
              name: spark-logs
          securityContext:
            privileged: true

      volumes:
        - name: spark-logs
          emptyDir: {}

      restartPolicy: Always
  selector:
    matchLabels:
      app: spark-zeppelin

---

# > minikube service spark-zeppelin-service --url

apiVersion: v1
kind: Service
metadata:
  name: spark-zeppelin-service
spec:
  type: LoadBalancer
  selector:
    app: spark-zeppelin
  ports:
    - name: zeppelin-web-service
      port: 8080
      targetPort: zeppelin-web
