apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-zeppelin-deployment
  labels:
    app: spark-zeppelin
spec:
  replicas: 1
  template:
    metadata:
      name: spark-zeppelin
      labels:
        app: spark-zeppelin
    spec:
      containers:
        - name: spark-zeppelin
          image: apache/zeppelin:0.8.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4040
              name: zeppelin-port
            - containerPort: 8080
              name: zeppelin-web
          env:
            - name: ZEPPELIN_NOTEBOOK_DIR
              value: /notebook
            - name: ZEPPELIN_LOG_DIR
              value: /logs
          command:
            - /zeppelin/bin/zeppelin.sh
          volumeMounts:
            - mountPath: /logs
              name: hostpath-logs
              readOnly: false
              mountPropagation: HostToContainer
            - mountPath: /notebook
              name: hostpath-notebook
              readOnly: false
              mountPropagation: HostToContainer
          securityContext:
            privileged: true

      volumes:
        - name: hostpath-logs
          hostPath:
            path: /Users/nhn/logs
            type: DirectoryOrCreate
        - name: hostpath-notebook
          hostPath:
            path: /Users/nhn/logs
            type: DirectoryOrCreate

      restartPolicy: Always
  selector:
    matchLabels:
      app: spark-zeppelin

---

# > minikube service spark-zeppelin-service --url

apiVersion: v1
kind: Service
metadata:
  name: spark-zeppelin-service
spec:
  type: LoadBalancer
  selector:
    app: spark-zeppelin
  ports:
    - name: zeppelin-web-service
      port: 8080
      targetPort: zeppelin-web

#---
#
#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: spark-zeppelin-pv
#spec:
#  capacity:
#    storage: 1Gi
#  volumeMode: Filesystem
#  accessModes:
#    - ReadWriteMany
#  storageClassName: zeppelin
#  persistentVolumeReclaimPolicy: Retain
#  hostPath:
#    path: /Users/nhn/logs
#    type: Directory
#
#
#---
#
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: spark-zeppelin-pvc
#spec:
#  accessModes:
#    - ReadWriteMany
#  volumeMode: Filesystem
#  resources:
#    requests:
#      storage: 1Gi
#  storageClassName: zeppelin
#
