apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: monitoring
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port:   '9090'
spec:
  selector:
    app: prometheus-server
  type: ClusterIP
  ports:
    - port: 9090
      targetPort: 9090

---

apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: prometheus-ing-class
  namespace: monitoring
  labels:
    app.kubernetes.io/component: controller
spec:
  controller: k8s.io/ingress-nginx

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prometheus-ingress
  namespace: monitoring
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  ingressClassName: prometheus-ing-class
  tls:
    - hosts:
        - "*.apps.psawesome.dev"
      secretName: secret-tls
  rules:
    - host: prometheus.apps.psawesome.dev
      http:
        paths:
          - backend:
              service:
                name: prometheus-service
                port:
                  number: 9090
            pathType: Prefix
            path: /

